### ISSUE TITLE
Feature request : Multiple examples for a parameter

### ISSUE THREAD

**Issue by sm2017** [Ysj291823/egg-swagger-doc#10]
Can you please implement **Multiple examples for a parameter:**

```yaml
parameters:
  - in: query
    name: limit
    schema:
      type: integer
      maximum: 50
    examples:       # Multiple examples
      zero:         # Distinct name
        value: 0    # Example value
        summary: A sample limit value # Optional description
      max: # Distinct name
        value: 50   # Example value
        summary: A sample limit value # Optional description
```
