### ISSUE TITLE
Feature request : Describing Parameters

### ISSUE THREAD

**Issue by sm2017** [Ysj291823/egg-swagger-doc#11]
Please implement `description` for Parameters

```yaml
paths:
  /users/{userId}:
    get:
      summary: Get a user by ID
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
```
