### ISSUE TITLE
@Scope

### ISSUE THREAD

**Issue by sm2017** [Ysj291823/egg-swagger-doc#31]
In config we can define scopes

```js
exports.swaggerdoc = {
...
  securityDefinitions: {
    oauth2: {
       type: 'oauth2',
       tokenUrl: 'http://petstore.swagger.io/oauth/dialog',
       flow: 'password',
       scopes: {
         'write:access_token': 'write access_token',
         'read:access_token': 'read access_token',
       },
     },
  },
...
};
```

But , I think there is no option to document , what scope needed to access a method , so `@scope` is needed

**Comment by Ysj291823** [comment]
you can use @oauth2,which you defined

**Comment by sm2017** [comment]
It's hard and dirty, I must define grants , endpoint each time

**Comment by sm2017** [comment]
see https://swagger.io/docs/specification/authentication/oauth2/


```yaml 
omponents/securitySchemes section:
components:
  securitySchemes:
    oAuthSample:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_pets: read pets in your account
            write_pets: modify pets in your account
```


```yaml
paths:
  /pets/{petId}:
    patch:
      summary: Updates a pet in the store
      security: 
        - oAuthSample: [write_pets]
      ...
```
